### ISSUE TITLE
Problem about compile and symbol lookup error

### ISSUE THREAD

**Issue by dc-daichao95** [Microsoft/Freeflow#16]
### Problem
Sorry to bother you. I'm reproducing Freeflow on my own machine. At first, Some compilation problems encountered and I fix it with **[gangliao/k8s-freeflow](https://github.com/gangliao/k8s-freeflow)** methods(change some compile options). After I finish the compilation, I run ib_send_bw, An error happens as below:
`### FreeFlow ###
libibverbs: Warning: couldn't load driver 'mlx5': /lib64/libmlx5-rdmav2.so: symbol ibv_exp_cmd_create_srq, version IBVERBS_1.1 not defined in file libibverbs.so.1 with link time reference
ib_send_bw: symbol lookup error: /usr/lib/libibverbs.so.1: undefined symbol: mempool_create`

### Environment
OS: centos7.4.1708 with Linux Kernel 3.10.0-693.el7.x86_64
RMDA NIC: Mellanox Technologies MT27500 Family [ConnectX-3]
OFED version:MLNX_OFED_LINUX-4.0-2.0.0.1-rhel7.4-x86_64
Docker version: Docker version 1.13.1
weave: 2.5.2
gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) 

 I hope I can get your help or anyone's help, Thank you very much !

**Comment by JinBoZi** [comment]
I think i encounter similar problem,why this issue be close?Have you slove this question?can you help me?Thanks!

When I compile libibverbs-1.2.1mlnx1, i have same error:

  CCLD     examples/ibv_devices
./src/.libs/libibverbs.so: undefined reference to `mempool_del'
./src/.libs/libibverbs.so: undefined reference to `mempool_insert'
./src/.libs/libibverbs.so: undefined reference to `mempool_create'
./src/.libs/libibverbs.so: undefined reference to `mempool_get'
