### ISSUE TITLE
Does ffrouter accelerate TCP socket using RDMA?

### ISSUE THREAD

**Issue by rhiswell** [Microsoft/Freeflow#3]
Or just forward stream to host network?

**Comment by bobzhuyb** [comment]
No. If you want that, you can use freeflow in combination with rsocket.

The tcp branch has nothing to do with rdma. In a nutshell, it creates a short-cut in kernel for applications inside containers to avoid unnecessary kernel stack overhead.

**Comment by rhiswell** [comment]
Thanks.
