### ISSUE TITLE
pull access denied for exce

### ISSUE THREAD

**Issue by srangari** [Microsoft/Freeflow#5]
I have started the freeflow router and tried logging in ,getting below error. Please provide suggestions.

![error2-pull access denied](https://user-images.githubusercontent.com/38135622/48433901-48ce3280-e746-11e8-96b6-d3cab39af558.JPG)

**Comment by lampson0505** [comment]
type "sudo docker ps -a", you can see your existing containers, including the ones which are stopped. Based on your case, you need to "sudo docker rm -f router1" to remove the existing container and then create a new one.

**Comment by srangari** [comment]
Still the error continues. Below see the attached image.


![error3](https://user-images.githubusercontent.com/38135622/48505128-4b975900-e814-11e8-95d3-96391849b680.JPG)

**Comment by lampson0505** [comment]
sudo docker run exec --> sudo docker exec

**Comment by srangari** [comment]
Could you please suggest how to proceed further. I am getting error when we are asked to build code in build-router.sh
![freeflow4](https://user-images.githubusercontent.com/38135622/48858004-485a1b00-ed88-11e8-866a-17091c573836.JPG)
