### ISSUE TITLE
Fatal Error: infiniband/verbs_exp.h and Compilation terminated

### ISSUE THREAD

**Issue by srangari** [Microsoft/Freeflow#6]
Hello Team,
![make error](https://user-images.githubusercontent.com/38135622/49098376-b9904700-f23c-11e8-837c-c562100578e3.JPG)

I am working on the freeflow practical simulation and facing an error while runing build.sh file as described in Step 2.
Request you to please suggest some solution.

**Comment by lampson0505** [comment]
are you using exactly this OFED library? MLNX_OFED_LINUX-4.0-2.0.0.1-ubuntu14.04-x86_64.tgz?

**Comment by srangari** [comment]
Yes I am using the same OFED Library. Also I am getting another error while running **./configure --prefix=/usr/ --libdir=/usr/lib/ --sysconfdir=/etc/**
as shown in screenshot.
![libibverbs-error](https://user-images.githubusercontent.com/38135622/49609148-b0078d00-f968-11e8-8eb9-5f19d4500a27.JPG)

**Comment by srangari** [comment]
Yes I have used the same library as shown in screenshot , still getting the error. Kindly request you to help on the same.
![drivers](https://user-images.githubusercontent.com/38135622/49682289-dff58400-fa7f-11e8-8a13-f6f820f20ae4.jpg)
![github](https://user-images.githubusercontent.com/38135622/49682292-fb608f00-fa7f-11e8-8c22-f49e9d0fb308.JPG)

**Comment by bobzhuyb** [comment]
You need to install Mellanox OFED driver. From your wget screenshot, you didn't really download/install it... Use your browser to open the link and download. It's much larger than what you got.

**Comment by srangari** [comment]
Thank you I am able to download the correct version of Mellanox OFED driver. However again got new error while installing as shown in screenshot saying one or more packages are missing. Could you please suggest commands to solve this.
![error while mlnx install](https://user-images.githubusercontent.com/38135622/49692403-446c1e00-fb28-11e8-828c-7263605d4b3b.JPG)

**Comment by bobzhuyb** [comment]
This is not related to Freeflow. This is a Mellanox OFED installation issue, or it could be your docker container issue.

It seems that apt-get cannot run properly to install Mellanox OFED prerequisites.
